Update to v7 tag documentation for compatibility with devtools (#522)
* Update to v7 tag for compatibility

I ran into an issue using the wrong version with the v7 with v2 of devtools with `typeError: getValues is not a function` via npm tag https://www.npmjs.com/package/@hookform/devtools

* docs: Update text for next tag for devtools to display